---
title: "Project"
author: "Xinan Wang"
date: "2023-02-25"
output: pdf_document
---

```{r setup, include=FALSE}
# echo=T to show the code, eval=T to show the results ----
knitr::opts_chunk$set(echo = T, eval=T) 
# Pre-load packages ----
library(tidyverse) 
library(ggplot2)
library(datasets)
library(dplyr)
library(haven)
library(readxl)
library(caret)
library(maps)
library(countrycode)
```

# Set file path
```{r}
#file_path <- "/Users/nannmemeda/Desktop/IE 6600/project/JMP_2021_WLD.xlsx"
file_path <- "/Users/tomokikyotani/Documents/Northeastern/Courses/Spring2023/IE6600/Project/JMP_2021_WLD.xlsx"
```


# Water data
```{r}
water_data <- read_excel(file_path, sheet = "Water")

water_data <- rename(water_data, 'NATIONAL_At least basic' = 'NATIONAL')
water_data <- rename(water_data, 'RURAL_At least basic' = 'RURAL')
water_data <- rename(water_data, 'URBAN_At least basic' = 'URBAN')
water_data <- rename(water_data, 'NATIONAL_PROP_Safely managed' = 'NATIONAL_PROP')
water_data <- rename(water_data, 'RURAL_PROP_Safely managed' = 'RURAL_PROP')
water_data <- rename(water_data, 'URBAN_PROP_Safely managed' = 'URBAN_PROP')

column_names <- c(
  "NATIONAL_Limited (more than 30 mins)",
  "NATIONAL_Unimproved",
  "NATIONAL_Surface water",
  "NATIONAL_Annual rate of change in basic",
  "RURAL_Limited (more than 30 mins)",
  "RURAL_Unimproved",
  "RURAL_Surface water",
  "RURAL_Annual rate of change in basic",
  "URBAN_Limited (more than 30 mins)",
  "URBAN_Unimproved",
  "URBAN_Surface water",
  "URBAN_Annual rate of change in basic",
  "NATIONAL_PROP_Accessible on premises",
  "NATIONAL_PROP_Available when needed",
  "NATIONAL_PROP_Free from contamination",
  "NATIONAL_PROP_Annual rate of change in safely managed",
  "NATIONAL_PROP_Piped",
  "NATIONAL_PROP_Non-piped",
  "RURAL_PROP_Accessible on premises",
  "RURAL_PROP_Available when needed",
  "RURAL_PROP_Free from contamination",
  "RURAL_PROP_Annual rate of change in safely managed",
  "RURAL_PROP_Piped",
  "RURAL_PROP_Non-piped",
  "URBAN_PROP_Accessible on premises",
  "URBAN_PROP_Available when needed",
  "URBAN_PROP_Free from contamination",
  "URBAN_PROP_Annual rate of change in safely managed",
  "URBAN_PROP_Piped",
  "URBAN_PROP_Non-piped",
  "SI"
)

water_data <- water_data %>% rename_with(~column_names, starts_with("..."))

water_data <- water_data[-c(1,2),]
water_data <- water_data %>% select(-SI)
water_data <- water_data %>% mutate_all(~ifelse(. == "-", NA, .))



# Clean the non-numeric values such as "<1", ">99"
# For now, "<1" is replaced with 0.5, and ">99" is replaced with 99.5
water_data %>%
  filter_all(any_vars(. %in% c("<1", ">99")))

water_data <- water_data %>% mutate_all(~ifelse(. == "<1", 0.5, .))
water_data <- water_data %>% mutate_all(~ifelse(. == ">99", 99.5, .))

str(water_data)

# Gives no warning such as "NAs introduced by coercion", and the mutation was successful
water_data <- water_data %>%
  mutate_at(6:41, as.numeric)


### Convert wide to long format
water_data_national <- water_data %>%
  select(c(1:5, 6:10, 21:27, 42:45)) %>%
  mutate(Region = "National")

water_data_rural <- water_data %>%
  select(c(1:5, 11:15, 28:34, 42:45)) %>%
  mutate(Region = "Rural")

water_data_urban <- water_data %>%
  select(c(1:5, 16:20, 35:41, 42:45)) %>%
  mutate(Region = "Urban")

str(water_data_national)
str(water_data_rural)
str(water_data_urban)

# Rename column names so that we can merge 3 data frames
dput(names(water_data_national))

final_column_names_water <- c("COUNTRY, AREA OR TERRITORY", "ISO3", "Year", "Population (thousands)",
"% urban", "At least basic", "Limited (more than 30 mins)", 
"Unimproved", "Surface water", "Annual rate of change in basic", 
"PROP_Safely managed", "PROP_Accessible on premises", 
"PROP_Available when needed", "PROP_Free from contamination", 
"PROP_Annual rate of change in safely managed", "PROP_Piped", 
"PROP_Non-piped", "SDG region", "WHO region", "UNICEF Programming region", 
"UNICEF Reporting region", "Region")

names(water_data_national) <- final_column_names_water
names(water_data_rural) <- final_column_names_water
names(water_data_urban) <- final_column_names_water

water_data_long <- rbind(water_data_national, water_data_rural, water_data_urban)


## Prepare data for mapping
mapWorld <- map_data("world")

mapWorld$ISO3 <- countrycode(mapWorld$region, "country.name", "iso3c")
# Warning message:
#   In countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest,  :
#                            Some values were not matched unambiguously: Ascension Island, 
#                          Azores, Barbuda, Bonaire, Canary Islands, Chagos Archipelago, Grenadines, 
#                          Heard Island, Kosovo, Madeira Islands, Micronesia, Saba, Saint Martin, 
#                          Siachen Glacier, Sint Eustatius, Virgin Islands


# Manually assign ISO3 codes to the countries above:
mapWorld[mapWorld$region == "Ascension Island", "ISO3"] <- "SHN"
mapWorld[mapWorld$region == "Azores", "ISO3"] <- "AZO"
mapWorld[mapWorld$region == "Barbuda", "ISO3"] <- "ATG"
mapWorld[mapWorld$region == "Bonaire", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Chagos Archipelago", "ISO3"] <- "IOT"
mapWorld[mapWorld$region == "Grenadines", "ISO3"] <- "VCT"
mapWorld[mapWorld$region == "Heard Island", "ISO3"] <- "HMD"
mapWorld[mapWorld$region == "Kosovo", "ISO3"] <- "XXK"
mapWorld[mapWorld$region == "Madeira Islands", "ISO3"] <- "MDI"
mapWorld[mapWorld$region == "Micronesia", "ISO3"] <- "FSM"
mapWorld[mapWorld$region == "Saba", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Saint Martin", "ISO3"] <- "MAF"
mapWorld[mapWorld$region == "Sint Eustatius", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Virgin Islands", "ISO3"] <- "VIR"

water_data_mapping <- mapWorld%>%
  inner_join(water_data_long, by = "ISO3")

# Export the data
write.csv(water_data_mapping, 
          '/Users/tomokikyotani/Local/NU/Spring2023_local/IE6600/DrinkingWater-Sanitation-Hygiene-Visualization/shinyApp/www/datasets/water_map.csv', 
          row.names=FALSE)



## The transformed data file above is almost 2GB in size. For our demo purpose, I'll reduce the size.

water_data_mapping_reduced <- water_data_mapping %>%
  filter(Year >= 2018)

write.csv(water_data_mapping_reduced, 
          '/Users/tomokikyotani/Local/NU/Spring2023_local/IE6600/DrinkingWater-Sanitation-Hygiene-Visualization/shinyApp/www/datasets/water_map_reduced.csv', 
          row.names=FALSE)
```


# Sanitation data
```{r}
sanitation_data <- read_excel(file_path, sheet = "Sanitation")

sanitation_data <- rename(sanitation_data, 'NATIONAL_At least basic' = 'NATIONAL...6')
sanitation_data <- rename(sanitation_data, 'RURAL_At least basic' = 'RURAL...12')
sanitation_data <- rename(sanitation_data, 'URBAN_At least basic' = 'URBAN...18')
sanitation_data <- rename(sanitation_data, 'NATIONAL_Exc_Safely managed' = 'NATIONAL...24')
sanitation_data <- rename(sanitation_data, 'NATIONAL_Inc_Latrines and others' = '...29')
sanitation_data <- rename(sanitation_data, 'RURAL_Exc_Safely managed' = 'RURAL...32')
sanitation_data <- rename(sanitation_data, 'RURAL_Inc_Latrines and others' = '...37')
sanitation_data <- rename(sanitation_data, 'URBAN_Exc_Safely managed' = 'URBAN...40')
sanitation_data <- rename(sanitation_data, 'URBAN_Inc_Latrines and others' = '...45')

column_names <- c(
  "NATIONAL_Limited (shared)",
  "NATIONAL_Unimproved",
  "NATIONAL_Open defecation",
  "NATIONAL_Annual rate of change in basic",
  "NATIONAL_Annual rate of change in open defecation",
  "RURAL_Limited (shared)",
  "RURAL_Unimproved",
  "RURAL_Open defecation",
  "RURAL_Annual rate of change in basic",
  "RURAL_Annual rate of change in open defecation",
  "URBAN_Limited (shared)",
  "URBAN_Unimproved",
  "URBAN_Open defecation",
  "URBAN_Annual rate of change in basic",
  "URBAN_Annual rate of change in open defecation",
  "NATIONAL_Exc_Disposed in situ",
  "NATIONAL_Exc_Emptied and treated",
  "NATIONAL_Exc_Wastewater treated",
  "NATIONAL_Exc_Annual rate of change in safely managed",
  "NNATIONAL_Inc_Septic tanks",
  "NATIONAL_Inc_Sewer connections",
  "RURAL_Exc_Disposed in situ",
  "RURAL_Exc_Emptied and treated",
  "RURAL_Exc_Wastewater treated",
  "RURAL_Exc_Annual rate of change in safely managed",
  "RURAL_Inc_Septic tanks",
  "RURAL_Inc_Sewer connections",
  "URBAN_Exc_Disposed in situ",
  "URBAN_Exc_Emptied and treated",
  "URBAN_Exc_Wastewater treated",
  "URBAN_Exc_Annual rate of change in safely managed",
  "URBAN_Inc_Septic tanks",
  "URBAN_Inc_Sewer connections",
  "SI"
)

sanitation_data <- sanitation_data %>% rename_with(~column_names, starts_with("..."))

sanitation_data <- sanitation_data[-c(1,2),]
sanitation_data <- sanitation_data %>% select(-SI)
sanitation_data <- sanitation_data %>% mutate_all(~ifelse(. == "-", NA, .))



# Clean the non-numeric values such as "<1", ">99"
# For now, "<1" is replaced with 0.5, and ">99" is replaced with 99.5
sanitation_data %>%
  filter_all(any_vars(. %in% c("<1", ">99")))

sanitation_data <- sanitation_data %>% mutate_all(~ifelse(. == "<1", 0.5, .))
sanitation_data <- sanitation_data %>% mutate_all(~ifelse(. == ">99", 99.5, .))

str(sanitation_data)

# Gives no warning such as "NAs introduced by coercion", and the mutation was successful
sanitation_data <- sanitation_data %>%
  mutate_at(6:47, as.numeric)


### Convert wide to long format
sanitation_data_national <- sanitation_data %>%
  select(c(1:5, 6:11, 24:31, 48:51)) %>%
  mutate(Region = "National")

sanitation_data_rural <- sanitation_data %>%
  select(c(1:5, 12:17, 32:39, 48:51)) %>%
  mutate(Region = "Rural")

sanitation_data_urban <- sanitation_data %>%
  select(c(1:5, 18:23, 40:47, 48:51)) %>%
  mutate(Region = "Urban")

str(sanitation_data_national)
str(sanitation_data_rural)
str(sanitation_data_urban)

# Rename column names so that we can merge 3 data frames
dput(names(sanitation_data_national))

final_column_names_sanitation <- c("COUNTRY, AREA OR TERRITORY", "ISO3", "Year", "Population (thousands)", 
"% urban", "At least basic", "Limited (shared)", "Unimproved", "Open defecation", "Annual rate of change in basic", 
"Annual rate of change in open defecation", "Exc_Safely managed", "Exc_Disposed in situ", "Exc_Emptied and treated", 
"Exc_Wastewater treated", "Exc_Annual rate of change in safely managed", "Inc_Latrines and others", "Inc_Septic tanks", "Inc_Sewer connections", "SDG region", "WHO region", 
"UNICEF Programming region", "UNICEF Reporting region", "Region")

names(sanitation_data_national) <- final_column_names_sanitation
names(sanitation_data_rural) <- final_column_names_sanitation
names(sanitation_data_urban) <- final_column_names_sanitation

sanitation_data_long <- rbind(sanitation_data_national, sanitation_data_rural, sanitation_data_urban)
unique(sanitation_data_long$Region)




## Prepare data for mapping
mapWorld <- map_data("world")

mapWorld$ISO3 <- countrycode(mapWorld$region, "country.name", "iso3c")
# Warning message:
#   In countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest,  :
#                            Some values were not matched unambiguously: Ascension Island, 
#                          Azores, Barbuda, Bonaire, Canary Islands, Chagos Archipelago, Grenadines, 
#                          Heard Island, Kosovo, Madeira Islands, Micronesia, Saba, Saint Martin, 
#                          Siachen Glacier, Sint Eustatius, Virgin Islands


# Manually assign ISO3 codes to the countries above:
mapWorld[mapWorld$region == "Ascension Island", "ISO3"] <- "SHN"
mapWorld[mapWorld$region == "Azores", "ISO3"] <- "AZO"
mapWorld[mapWorld$region == "Barbuda", "ISO3"] <- "ATG"
mapWorld[mapWorld$region == "Bonaire", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Chagos Archipelago", "ISO3"] <- "IOT"
mapWorld[mapWorld$region == "Grenadines", "ISO3"] <- "VCT"
mapWorld[mapWorld$region == "Heard Island", "ISO3"] <- "HMD"
mapWorld[mapWorld$region == "Kosovo", "ISO3"] <- "XXK"
mapWorld[mapWorld$region == "Madeira Islands", "ISO3"] <- "MDI"
mapWorld[mapWorld$region == "Micronesia", "ISO3"] <- "FSM"
mapWorld[mapWorld$region == "Saba", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Saint Martin", "ISO3"] <- "MAF"
mapWorld[mapWorld$region == "Sint Eustatius", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Virgin Islands", "ISO3"] <- "VIR"

sanitation_data_mapping <- mapWorld%>%
  inner_join(sanitation_data_long, by = "ISO3")


# Reduce the data and export the data
sanitation_data_mapping_reduced <- sanitation_data_mapping %>%
  filter(Year >= 2018)

write.csv(sanitation_data_mapping_reduced, 
          '/Users/tomokikyotani/Local/NU/Spring2023_local/IE6600/DrinkingWater-Sanitation-Hygiene-Visualization/shinyApp/www/datasets/sanitation_map_reduced.csv', 
          row.names=FALSE)
```


# Hyginene data
```{r}
hygiene_data <- read_excel(file_path, sheet = "Hygiene")

hygiene_data <- rename(hygiene_data, 'NATIONAL_Basic' = 'NATIONAL')
hygiene_data <- rename(hygiene_data, 'NATIONAL_Limited (without water or soap)' = '...7')
hygiene_data <- rename(hygiene_data, 'NATIONAL_No facility' = '...8')
hygiene_data <- rename(hygiene_data, 'NATIONAL_Annual rate of change in basic' = '...9')
hygiene_data <- rename(hygiene_data, 'RURAL_Basic' = 'RURAL')
hygiene_data <- rename(hygiene_data, 'RURAL_Limited (without water or soap)' = '...11')
hygiene_data <- rename(hygiene_data, 'RURAL_No facility' = '...12')
hygiene_data <- rename(hygiene_data, 'RURAL_Annual rate of change in basic' = '...13')
hygiene_data <- rename(hygiene_data, 'URBAN_Basic' = 'URBAN')
hygiene_data <- rename(hygiene_data, 'URBAN_Limited (without water or soap)' = '...15')
hygiene_data <- rename(hygiene_data, 'URBAN_No facility' = '...16')
hygiene_data <- rename(hygiene_data, 'URBAN_Annual rate of change in basic' = '...17')
hygiene_data <- rename(hygiene_data, 'SI' = '...18')
hygiene_data <- rename(hygiene_data, 'SDG region' = '...19')
hygiene_data <- rename(hygiene_data, 'WHO region' = '...20')
hygiene_data <- rename(hygiene_data, 'UNICEF Programming region' = '...21')
hygiene_data <- rename(hygiene_data, 'UNICEF Reporting region' = '...22')

hygiene_data <- hygiene_data[-c(1),]
hygiene_data <- hygiene_data %>% select(-SI)
hygiene_data <- hygiene_data %>% mutate_all(~ifelse(. == "-", NA, .))



# Clean the non-numeric values such as "<1", ">99"
# For now, "<1" is replaced with 0.5, and ">99" is replaced with 99.5
hygiene_data %>%
  filter_all(any_vars(. %in% c("<1", ">99")))

hygiene_data <- hygiene_data %>% mutate_all(~ifelse(. == "<1", 0.5, .))
hygiene_data <- hygiene_data %>% mutate_all(~ifelse(. == ">99", 99.5, .))

str(hygiene_data)

# Gives no warning such as "NAs introduced by coercion", and the mutation was successful
hygiene_data <- hygiene_data %>%
  mutate_at(6:17, as.numeric)


### Convert wide to long format
hygiene_data_national <- hygiene_data %>%
  select(c(1:5, 6:9, 18:21)) %>%
  mutate(Region = "National")

hygiene_data_rural <- hygiene_data %>%
  select(c(1:5, 10:13, 18:21)) %>%
  mutate(Region = "Rural")

hygiene_data_urban <- hygiene_data %>%
  select(c(1:5, 14:17, 18:21)) %>%
  mutate(Region = "Urban")

str(hygiene_data_national)
str(hygiene_data_rural)
str(hygiene_data_urban)

# Rename column names so that we can merge 3 data frames
dput(names(hygiene_data_national))

final_column_names_hygiene <- c("COUNTRY, AREA OR TERRITORY", "ISO3", "Year", "Population (thousands)", 
"% urban", "Basic", "Limited (without water or soap)", "No facility", "Annual rate of change in basic", 
"SDG region", "WHO region", "UNICEF Programming region", "UNICEF Reporting region", 
"Region")

names(hygiene_data_national) <- final_column_names_hygiene
names(hygiene_data_rural) <- final_column_names_hygiene
names(hygiene_data_urban) <- final_column_names_hygiene

hygiene_data_long <- rbind(hygiene_data_national, hygiene_data_rural, hygiene_data_urban)
unique(hygiene_data_long$Region)

hygiene_data_long



## Prepare data for mapping
mapWorld <- map_data("world")

mapWorld$ISO3 <- countrycode(mapWorld$region, "country.name", "iso3c")
# Warning message:
#   In countrycode_convert(sourcevar = sourcevar, origin = origin, destination = dest,  :
#                            Some values were not matched unambiguously: Ascension Island, 
#                          Azores, Barbuda, Bonaire, Canary Islands, Chagos Archipelago, Grenadines, 
#                          Heard Island, Kosovo, Madeira Islands, Micronesia, Saba, Saint Martin, 
#                          Siachen Glacier, Sint Eustatius, Virgin Islands


# Manually assign ISO3 codes to the countries above:
mapWorld[mapWorld$region == "Ascension Island", "ISO3"] <- "SHN"
mapWorld[mapWorld$region == "Azores", "ISO3"] <- "AZO"
mapWorld[mapWorld$region == "Barbuda", "ISO3"] <- "ATG"
mapWorld[mapWorld$region == "Bonaire", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Chagos Archipelago", "ISO3"] <- "IOT"
mapWorld[mapWorld$region == "Grenadines", "ISO3"] <- "VCT"
mapWorld[mapWorld$region == "Heard Island", "ISO3"] <- "HMD"
mapWorld[mapWorld$region == "Kosovo", "ISO3"] <- "XXK"
mapWorld[mapWorld$region == "Madeira Islands", "ISO3"] <- "MDI"
mapWorld[mapWorld$region == "Micronesia", "ISO3"] <- "FSM"
mapWorld[mapWorld$region == "Saba", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Saint Martin", "ISO3"] <- "MAF"
mapWorld[mapWorld$region == "Sint Eustatius", "ISO3"] <- "BES"
mapWorld[mapWorld$region == "Virgin Islands", "ISO3"] <- "VIR"

hygiene_data_mapping <- mapWorld%>%
  inner_join(hygiene_data_long, by = "ISO3")


# Reduce the data and export the data
hygiene_data_mapping_reduced <- hygiene_data_mapping %>%
  filter(Year >= 2018)

write.csv(hygiene_data_mapping_reduced, 
          '/Users/tomokikyotani/Local/NU/Spring2023_local/IE6600/DrinkingWater-Sanitation-Hygiene-Visualization/shinyApp/www/datasets/hygiene_map_reduced.csv', 
          row.names=FALSE)
```


### Regression Model
```{r}

features <- c(
  "COUNTRY, AREA OR TERRITORY",
  "Year",
  "Population \r\n(thousands)",
  "% urban",
  "NATIONAL_At least basic",
  "NATIONAL_Limited (more than 30 mins)",
  "NATIONAL_Unimproved",
  "NATIONAL_Surface water",
  "NATIONAL_Annual rate of change in basic",
  "NATIONAL_PROP_Safely managed"
)

water_features <- water_data %>% select(all_of(features))

### Already converted to numeric
# water_features$"NATIONAL_At least basic" <- as.numeric(water_features$"NATIONAL_At least basic")
# water_features$"NATIONAL_Limited (more than 30 mins)" <- as.numeric(water_features$"NATIONAL_Limited (more than 30 mins)")
# water_features$"NATIONAL_Unimproved" <- as.numeric(water_features$"NATIONAL_Unimproved")
# water_features$"NATIONAL_Surface water" <- as.numeric(water_features$"NATIONAL_Surface water")
# water_features$"NATIONAL_Annual rate of change in basic" <- as.numeric(water_features$"NATIONAL_Annual rate of change in basic")
# water_features$"NATIONAL_PROP_Safely_managed" <- as.numeric(water_features$"NATIONAL_PROP_Safely managed")

water_features <- water_features %>% select(-`NATIONAL_PROP_Safely managed`)

water_features <- drop_na(water_features)

water_features$`COUNTRY, AREA OR TERRITORY` <- as_factor(water_features$`COUNTRY, AREA OR TERRITORY`)
water_features$`Country_index` <- as.integer(water_features$`COUNTRY, AREA OR TERRITORY`)

set.seed(123)
trainIndex <- sample(nrow(water_features), round(0.8*nrow(water_features)),replace = FALSE)
water_data_train <- water_features[trainIndex, ]
water_data_test <- water_features[-trainIndex, ]

fit <- lm(NATIONAL_PROP_Safely_managed ~ ., data = water_data_train)

water_data_test$NATIONAL_PROP_Safely_managed <- as.numeric(as.character(water_data_test$NATIONAL_PROP_Safely_managed))
pred <- predict(fit, newdata = water_data_test)

rmse <- RMSE(pred, water_data_test$NATIONAL_PROP_Safely_managed)
rsq <- R2(pred, water_data_test$NATIONAL_PROP_Safely_managed)

print(paste0("Root Mean Squared Error: ", round(rmse, 4)))
print(paste0("R Squared: ", round(rsq, 4)))

```